# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    - os: linux
      sudo: false
      r: release
    - os: osx
      r: release
      osx_image: xcode7.3
      latex: false
